# Based on https://github.com/cloudera/hue/tree/master/tools/docker
FROM ubuntu:trusty

MAINTAINER diogo.melo@b2wdigital.com

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:webupd8team/java


RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

RUN apt-get update && apt-get install --fix-missing -y \
    oracle-java8-installer \
    git \
    ant \
    gcc \
    g++ \
    libkrb5-dev \
    libmysqlclient-dev \
    libssl-dev \
    libsasl2-dev \
    libsasl2-modules-gssapi-mit \
    libsqlite3-dev \
    libtidy-0.99-0 \
    libxml2-dev \
    libxslt-dev \
    libffi-dev \
    make \
    maven \
    libldap2-dev \
    python-dev \
    python-setuptools \
    libgmp3-dev \
    libz-dev \
    && apt-get clean

RUN git clone https://github.com/cloudera/hue.git

WORKDIR hue

RUN make apps

COPY configs/hue/pseudo-distributed.ini desktop/conf/

# Nosso host cdh
ENV CDH_HOST=cdh

RUN sed -i s/__HOSTNAME__/$CDH_HOST/g desktop/conf/pseudo-distributed.ini

CMD ["build/env/bin/hue", "runserver_plus", "0.0.0.0:8888"]